apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-k8s-sentinel-sa
  namespace: service-discovery
  labels:
    app.kubernetes.io/name: posadev-go-sentinel
    app.kubernetes.io/component: serviceaccount
  annotations:
    # EKS Pod Identity mapping to IAM role for S3 access
    eks.amazonaws.com/role-arn: arn:aws:iam::443311183770:role/dev-eks-cluster-go-k8s-sentinel

