pipeline:
  name: demo2
  identifier: demo2
  projectIdentifier: demos
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jcroyoaun
        repoName: lessons
        build: <+input>
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: step1
                  identifier: step1
                  spec:
                    shell: Sh
                    command: echo "I'm not an inline script. I'm versioned in GitHub now"
